### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by StephenLee2016** [quick-trade/quick_trade#471]
Hi, Vlad. I have recently noticed your Quick Trade project, which is very concise and elegant, but I have a question: you haven't submitted any new updates for a long time, is it because you have given up on this project?

**Comment by VladKochetov007** [comment]
Hi. Actually, yes. I didn't want to say this, but I've started to have significant doubts about the project's architecture. From the perspective of optimization algorithms, it would also be much better to generalize the interaction interface.

The code in quick_trade has started to seem poorly structured to me, and I began developing [xoney](https://github.com/quick-trade/xoney_py). It currently lacks documentation and strategy examples, but it is more suited for developing event-based strategies.

Open-source development is temporarily on hold as exams are coming up, and I need to work on non-public projects.
